name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "📣 Breaking Changes"
    labels:
      - "breaking_change"
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    labels:
      - "maintenance"
  - title: "📚 Documentation"
    labels:
      - "documentation"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - "major"
      - "breaking_change"
  minor:
    labels:
      - "minor"
      - "feature"
      - "enhancement"
  patch:
    labels:
      - "patch"
      - "fix"
      - "bugfix"
      - "bug"
      - "maintenance"
      - "documentation"
  default: patch
autolabeler:
  - label: "github structure"
    files:
      - ".github/*"
  - label: "documentation"
    files:
      - "*.md"
  - label: "bug"
    title:
      - "/\\[?(bug)\\]?.*/i"
  - label: "bugfix"
    title:
      - "/\\[?(fix)\\]?.*/i"
  - label: "feature"
    title:
      - "/\\[?(add|feat)\\]?.*/i"
  - label: "feature"
    title:
      - "/\\[?(breaking)\\]?.*/i"
template: |
  ## Changes
  $CHANGES
